### ISSUE TITLE
Calendar dropdown font is wrong

### ISSUE THREAD

**Issue by JasonEtco** [ossfriday/ossfriday#136]
The font for the list-items in the Add To Calendar dropdown is "Verdana" - we can change that with some specific selectors:

<img width="370" alt="screen shot 2017-08-04 at 11 15 36 am" src="https://user-images.githubusercontent.com/10660468/28981382-68ad61f2-7906-11e7-8215-da043ffcee8a.png">

To fix it, we can add:

```scss
.atcb-item-link { font-family: $body-font !important; }
```

Let me know if y'all want to see a PR 👍
